#TODO: Understand how to use Dependabot 
# and how to configure it for this project
# dependabot configuration file for GitHub Actions

# version: 2
# updates:
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: "docker"
#     directory: "/"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: "pip"
#     directory: "/requirements"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "daily"
