"""Matchup ck_no_self_matchup and sorted ids

Revision ID: 0fd4e5926f4d
Revises: da32c858149f
Create Date: 2025-06-19 23:37:26.602273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd4e5926f4d'
down_revision = 'da32c858149f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_contestant_matchup'), type_='unique')
        batch_op.create_unique_constraint('uq_matchup_pair', ['contestant_a_id', 'contestant_b_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_constraint('uq_matchup_pair', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_contestant_matchup'), ['contestant_a_id', 'contestant_b_id'])

    # ### end Alembic commands ###
