"""implement Vote table

Revision ID: 6302c2b4c35d
Revises: 0fd4e5926f4d
Create Date: 2025-06-27 04:09:57.803922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6302c2b4c35d'
down_revision = '0fd4e5926f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestant.id'], ),
    sa.ForeignKeyConstraint(['matchup_id'], ['matchup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matchup_id', 'session_id', name='uq_vote_matchup_session')
    )
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_contestant_id'), ['contestant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_matchup_id'), ['matchup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_timestamp'))
        batch_op.drop_index(batch_op.f('ix_vote_session_id'))
        batch_op.drop_index(batch_op.f('ix_vote_matchup_id'))
        batch_op.drop_index(batch_op.f('ix_vote_country_code'))
        batch_op.drop_index(batch_op.f('ix_vote_contestant_id'))

    op.drop_table('vote')
    # ### end Alembic commands ###
