"""implement contestant img into table

Revision ID: 8f5b09fb10fb
Revises: 644c75f3244e
Create Date: 2025-09-16 03:11:14.646197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5b09fb10fb'
down_revision = '644c75f3244e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contestant_img', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contestant', schema=None) as batch_op:
        batch_op.drop_column('contestant_img')

    # ### end Alembic commands ###
