"""bps voting imported in api views py

Revision ID: b16d918f96a2
Revises: 894173f5f77d
Create Date: 2025-06-19 19:41:37.261852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16d918f96a2'
down_revision = '894173f5f77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contestant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestant_name', sa.String(length=64), nullable=False),
    sa.Column('contestant_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contestant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contestant_contestant_name'), ['contestant_name'], unique=True)

    op.create_table('matchup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contestant_a_id', sa.Integer(), nullable=False),
    sa.Column('contestant_b_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contestant_a_id'], ['contestant.id'], ),
    sa.ForeignKeyConstraint(['contestant_b_id'], ['contestant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchup_contestant_a_id'), ['contestant_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matchup_contestant_b_id'), ['contestant_b_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchup_contestant_b_id'))
        batch_op.drop_index(batch_op.f('ix_matchup_contestant_a_id'))

    op.drop_table('matchup')
    with op.batch_alter_table('contestant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contestant_contestant_name'))

    op.drop_table('contestant')
    # ### end Alembic commands ###
