"""implement Click Test table

Revision ID: d1cb3d5bf1ce
Revises: d918b1506d1b
Create Date: 2025-06-15 03:47:46.837884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cb3d5bf1ce'
down_revision = 'd918b1506d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_test',
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_test_click_count'), ['click_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('click_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_test_click_count'))

    op.drop_table('click_test')
    # ### end Alembic commands ###
