"""Matchup uq_contestand_ids

Revision ID: da32c858149f
Revises: ae53dfaaafa0
Create Date: 2025-06-19 23:24:31.010940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da32c858149f'
down_revision = 'ae53dfaaafa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_contestant_matchup', ['contestant_a_id', 'contestant_b_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matchup', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contestant_matchup', type_='unique')

    # ### end Alembic commands ###
